### ISSUE TITLE
As a	user	I want to use my mobile phone so that	I can connect like my email Assigned to: Tolga

### ISSUE THREAD

**Issue by tolgakb** [Agile-Software-Development-Group-B/CODE-RED-project#104]

**Comment by Ubaidkhan0502** [comment]
Please Mention the pull request. @tolgakb

**Comment by Ubaidkhan0502** [comment]
![image](https://user-images.githubusercontent.com/99564984/166834831-916e9415-19a8-422d-89ca-9a38815fab70.png)

PR Approved.
