### ISSUE TITLE
As a	user	I want a prompt to reactivate my account so that I can access my account after having disabled it. Assigned to: Nirmala

### ISSUE THREAD

**Issue by Chris-Codex** [Agile-Software-Development-Group-B/CODE-RED-project#60]

**Comment by nirmala2810** [comment]
![Task3](https://user-images.githubusercontent.com/99544048/165170904-d6474535-3723-4549-969f-3f26d0d3651a.png)

**Comment by nirmala2810** [comment]
To reactivate the account ,before that user should be prompted by a message showing his account is deactivated when the user tries to enter the organization using his email and password. The user can reactivate the account by selecting the buttons.
