### ISSUE TITLE
As a	user	I want to edit my default password after first time log in so that my password can't be retrieved by someone. Assigned to: Nirmala

### ISSUE THREAD

**Issue by Chris-Codex** [Agile-Software-Development-Group-B/CODE-RED-project#61]

**Comment by nirmala2810** [comment]
![Task2](https://user-images.githubusercontent.com/99544048/165171473-555186d2-cfc0-40b1-ab89-92b3cec17cec.png)
![Task2a1](https://user-images.githubusercontent.com/99544048/165171514-5546e8b5-aa92-4537-b889-3ff79ff33f58.png)
![Task2a2](https://user-images.githubusercontent.com/99544048/165171544-dea2cd1b-563b-4021-99c5-56ffc9a2ccea.png)

**Comment by nirmala2810** [comment]
The user can change his default password ,the default password may be his employee number or date of birth. The user can change his password in account settings->change password.
