### ISSUE TITLE
As a	user	I want to connect with my email and my password so that I can access the website. Assigned to: Nirmala

### ISSUE THREAD

**Issue by Chris-Codex** [Agile-Software-Development-Group-B/CODE-RED-project#62]

**Comment by nirmala2810** [comment]
[Task 1.docx](https://github.com/Agile-Software-Development-Group-B/CODE-RED-project/files/8546581/Task.1.docx)

**Comment by nirmala2810** [comment]
![Task1](https://user-images.githubusercontent.com/99544048/165170435-0573d288-06c1-4c17-a998-8909833c7ecc.png)
