### ISSUE TITLE
Create a login page that has email input field and password input field. Insert email and password into the various fields. If the email or password is incorrect let it flash a message that says email or password is incorrect, please try again. Assigned to: Chris

### ISSUE THREAD

**Issue by Chris-Codex** [Agile-Software-Development-Group-B/CODE-RED-project#92]

**Comment by Chris-Codex** [comment]
![1](https://user-images.githubusercontent.com/40234620/165460615-08b13ced-d629-45d4-859e-db3960372845.JPG)
![2](https://user-images.githubusercontent.com/40234620/165460690-c1fbdbc8-4ea3-49eb-b5a1-2201ff6c61f5.JPG)

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>CODE | RED</title>

  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  
  <link rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
  
  <link rel="stylesheet" href="../../plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  
  <link rel="stylesheet" href="../../dist/css/adminlte.min.css">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="../../index2.html"><b>CODE</b>RED</a>
  </div>
  
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Sign in to start your session</p>

      <form action="../../index3.html" method="post">
        <div class="input-group mb-3">
          <input type="email" class="form-control" placeholder="Email">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="Password"> 
        </div>
         <span class="fas" style="color: #FF0000; font-size:13px;">Username or password is incorrect. Please try again</span>
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="remember">
              <label for="remember">
                Remember Me
              </label>
            </div>
          </div>
          
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Sign In</button>
          </div>
          
        </div>
      </form>
    </div>
    
  </div>
</div>



<script src="../../plugins/jquery/jquery.min.js"></script>

<script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

<script src="../../dist/js/adminlte.min.js"></script>
</body>
</html>

**Comment by Ubaidkhan0502** [comment]
PR Approved.
