### ISSUE TITLE
As an employee: state the reason for exit: Assigned to: Raphael

### ISSUE THREAD

**Issue by RaphCtnh** [Agile-Software-Development-Group-B/CODE-RED-project#94]

**Comment by Ubaidkhan0502** [comment]
https://github.com/Agile-Software-Development-Group-B/CODE-RED-project/blob/94-as-an-employee-state-the-reason-for-exit-assigned-to-raphael/As%20an%20employee%20state%20the%20reason%20for%20exit.txt

He put screenshot this URL
