### ISSUE TITLE
As an employee, I want to view the allotted and earned leaves in a period, so that I can apply for leave in advance. Assigned to: Rapheal

### ISSUE THREAD

**Issue by RaphCtnh** [Agile-Software-Development-Group-B/CODE-RED-project#95]

**Comment by Ubaidkhan0502** [comment]
https://github.com/Agile-Software-Development-Group-B/CODE-RED-project/blob/95-as-an-employee-i-want-to-view-the-allotted-and-earned-leaves-in-a-period-so-that-i-can-apply-for-leave-in-advance-assigned-to-rapheal/As%20an%20employee%2C%20I%20want%20to%20view%20the%20allotted%20and%20earned%20leaves%20in%20a%20period%2C%20so%20that%20I%20can%20apply%20for%20leave%20in%20advance.docx

He Put Screenshot this URL
