### ISSUE TITLE
As an employee, I can enter the evaluation result in a drop down box and their opinion in a textfield form. Assigned to: Nirmala

### ISSUE THREAD

**Issue by nirmala2810** [Agile-Software-Development-Group-B/CODE-RED-project#96]

**Comment by nirmala2810** [comment]
![Evaluation1](https://user-images.githubusercontent.com/99544048/165645618-00d65c52-21f1-444a-8088-19720cc44958.png)

**Comment by nirmala2810** [comment]
The employer can select the evaluation result in the dropdown menu and corresponding to that comment in the text field.

**Comment by Ubaidkhan0502** [comment]
PR Approved.
