### ISSUE TITLE
As a	user	I want a disconnect button so that	the navigator forgets me and verify next time my identity. Assigned to: Nirmala

### ISSUE THREAD

**Issue by nirmala2810** [Agile-Software-Development-Group-B/CODE-RED-project#98]

**Comment by nirmala2810** [comment]
![Disconnect](https://user-images.githubusercontent.com/99544048/165789860-652512d2-f268-4c8d-ad88-039aa6e64f7c.png)

**Comment by nirmala2810** [comment]
User wants a disconnect option from the organization ,so that the id wont remains in the system.Everytime it asks for the identity once the user enters.

**Comment by Ubaidkhan0502** [comment]
PR Approved.
