### ISSUE TITLE
As an employee I will attend the exit interview. Assigned to: Chris

### ISSUE THREAD

**Issue by Chris-Codex** [Agile-Software-Development-Group-B/CODE-RED-project#99]

**Comment by Chris-Codex** [comment]
This module is to enable an employee effectively state his reason of leaving the organization for other necessary actions to be taken before he exists the organization.
![x](https://user-images.githubusercontent.com/40234620/165679565-330bd6c9-f2ca-4f4a-ad66-66f018debba7.JPG)

 
  <div class="content-wrapper">
    
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Employee Exit</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Employee Exit</li>
            </ol>
          </div>
        </div>
      </div>
    </section>

    
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-3">

            
            

            
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Profile</h3>
              </div>
              
              <div class="card-body">
                 <div class="text-center">
                  <img class="img-circle img-bordered-sm" src="../../dist/img/user1-128x128.jpg" alt="user image">
                </div>
                <strong><i class="fas fa-book mr-1"></i> Education</strong>

                <p class="text-muted">
                  B.S. in Computer Science from the University of Tennessee at Knoxville
                </p>

                <hr>

                <strong><i class="fas fa-book mr-1"></i> Department</strong>

                <p class="text-muted">
                  Software Development
                </p>

                <hr>

                <strong><i class="fas fa-map-marker-alt mr-1"></i> Location</strong>

                <p class="text-muted">Dublin, Ireland</p>

                <hr>

                <strong><i class="fas fa-pencil-alt mr-1"></i> Skills</strong>

                <p class="text-muted">
                  <span class="tag tag-danger">UI Design</span>
                  <span class="tag tag-success">Coding</span>
                  <span class="tag tag-info">Javascript</span>
                  <span class="tag tag-warning">PHP</span>
                  <span class="tag tag-primary">Node.js</span>
                </p>

                <hr>

                <strong><i class="far fa-file-alt mr-1"></i> Notes</strong>

                <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.</p>
              </div>
              
            </div>
            
          </div>
          
          <div class="col-md-9">
            <div class="card">
              <div class="card-header p-2">
              </div>
              <div class="card-body">
                <div class="tab-content">
                  <div class="active tab-pane" id="activity">
                    
                    <div class="post">
                      <div class="user-block">
                        <img class="img-circle img-bordered-sm" src="../../dist/img/user1-128x128.jpg" alt="user image">
                        <span class="username">
                          <a href="#">Nirmala Johnson</a>
                          <a href="#" class="float-right btn-tool"><i class="fas fa-times"></i></a>
                        </span>
                        <span class="description">Shared publicly - 7:30 PM today</span>
                      </div>
                      
                     <div class="card-body">
                <label>Employee Name:</label>
                <input class="form-control form-control-lg" type="text" placeholder="Nirmala Johnson" disabled>
                <br>
                <label>Employee Position:</label>
                <input class="form-control" type="text" placeholder="Software Developer" disabled>
                <br>
                <label>Employee Department:</label>
                <input class="form-control form-control-sm" type="text" placeholder="Software Development" disabled>
                <br>
                <label>Reason for Leaving:</label>
                <textarea class="form-control form-control-sm" type="text" placeholder="Enter reason for Leaving"></textarea> 

                <center><button class="btn btn-danger" style="margin-top:30px;">Confirm Exit</button></center>
              </div>
           </div>

**Comment by Ubaidkhan0502** [comment]
https://github.com/Agile-Software-Development-Group-B/CODE-RED-project/pull/105
